[2024-08-07T09:20:03.279+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T09:20:03.317+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.refresh_stages manual__2024-08-07T09:19:49.156848+00:00 [queued]>
[2024-08-07T09:20:03.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.refresh_stages manual__2024-08-07T09:19:49.156848+00:00 [queued]>
[2024-08-07T09:20:03.332+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T09:20:03.365+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): refresh_stages> on 2024-08-07 09:19:49.156848+00:00
[2024-08-07T09:20:03.370+0000] {standard_task_runner.py:63} INFO - Started process 5607 to run task
[2024-08-07T09:20:03.374+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'refresh_stages', 'manual__2024-08-07T09:19:49.156848+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location.dag.py', '--cfg-path', '/tmp/tmplu07fo55']
[2024-08-07T09:20:03.376+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask refresh_stages
[2024-08-07T09:20:03.461+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.refresh_stages manual__2024-08-07T09:19:49.156848+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T09:20:03.561+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'refresh_stages', field 'sql'. Template: "{ var.value.get('timelocation_data_dir') }/refresh.stage.sql"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: { var.value.get('timelocation_data_dir') }/refresh.stage.sql
[2024-08-07T09:20:03.564+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: { var.value.get('timelocation_data_dir') }/refresh.stage.sql
[2024-08-07T09:20:03.580+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=refresh_stages, run_id=manual__2024-08-07T09:19:49.156848+00:00, execution_date=20240807T091949, start_date=20240807T092003, end_date=20240807T092003
[2024-08-07T09:20:03.625+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task refresh_stages ({ var.value.get('timelocation_data_dir') }/refresh.stage.sql; 5607)
[2024-08-07T09:20:03.668+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T09:20:03.704+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T09:20:03.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
