[2024-08-09T08:44:59.874+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T08:44:59.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T08:44:14.350577+00:00 [queued]>
[2024-08-09T08:44:59.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T08:44:14.350577+00:00 [queued]>
[2024-08-09T08:44:59.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T08:44:59.963+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_atvsld> on 2024-08-09 08:44:14.350577+00:00
[2024-08-09T08:44:59.969+0000] {standard_task_runner.py:63} INFO - Started process 3528 to run task
[2024-08-09T08:44:59.974+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'gold_atvsld', 'manual__2024-08-09T08:44:14.350577+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmpmeje8hm5']
[2024-08-09T08:44:59.976+0000] {standard_task_runner.py:91} INFO - Job 407: Subtask gold_atvsld
[2024-08-09T08:45:00.077+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T08:44:14.350577+00:00 [running]> on host 45f7764b2bf2
[2024-08-09T08:45:00.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='gold_atvsld' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T08:44:14.350577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T08:44:14.350577+00:00'
[2024-08-09T08:45:00.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T08:45:08.503+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T08:45:08.504+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/gold/atvsld_gold.py", line 23, in run_gold_atvsld
    .load()
     ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 314, in load
    return self._df(self._jreader.load())
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: requirement failed: The driver could not open a JDBC connection. Check the URL: None:None/LdtbxhStage
[2024-08-09T08:45:08.554+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=gold_atvsld, run_id=manual__2024-08-09T08:44:14.350577+00:00, execution_date=20240809T084414, start_date=20240809T084459, end_date=20240809T084508
[2024-08-09T08:45:08.642+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 407 for task gold_atvsld (requirement failed: The driver could not open a JDBC connection. Check the URL: None:None/LdtbxhStage; 3528)
[2024-08-09T08:45:08.772+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-09T08:45:08.862+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T08:45:08.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
