[2024-08-07T07:55:19.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T07:55:19.380+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.query_postgres_database manual__2024-08-07T07:54:52.130219+00:00 [queued]>
[2024-08-07T07:55:19.430+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.query_postgres_database manual__2024-08-07T07:54:52.130219+00:00 [queued]>
[2024-08-07T07:55:19.431+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T07:55:19.498+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): query_postgres_database> on 2024-08-07 07:54:52.130219+00:00
[2024-08-07T07:55:19.508+0000] {standard_task_runner.py:63} INFO - Started process 4887 to run task
[2024-08-07T07:55:19.513+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'query_postgres_database', 'manual__2024-08-07T07:54:52.130219+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location.dag.py', '--cfg-path', '/tmp/tmpanwfrzv8']
[2024-08-07T07:55:19.516+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask query_postgres_database
[2024-08-07T07:55:19.644+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.query_postgres_database manual__2024-08-07T07:54:52.130219+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T07:55:19.854+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Time_Location_Dimension' AIRFLOW_CTX_TASK_ID='query_postgres_database' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T07:54:52.130219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T07:54:52.130219+00:00'
[2024-08-07T07:55:19.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T07:55:19.877+0000] {sql.py:276} INFO - Executing: INSERT INTO public."stgDate"(LocationKey, region_code, region_name,
                            province_code, province_name,
                            district_code, district_name,
                            ward_code, ward_name)
SELECT
	CAST(pro.province_code AS BIGINT)*100000000 + CAST(dist.district_code AS INTEGER)*100000 + CAST(w.ward_code AS INTEGER),
	re.region_code, region_name,
	pro.province_code, province_name,
	dist.district_code, district_name,
	w.ward_code, ward_name
FROM locations.region re
JOIN locations.province pro ON re.region_code = pro.region_code
JOIN locations.district dist ON dist.province_code = pro.province_code
JOIN locations.ward w ON w.district_code = dist.district_code 
[2024-08-07T07:55:19.901+0000] {base.py:84} INFO - Using connection ID 'postgres_hongheovna' for task execution.
[2024-08-07T07:55:20.242+0000] {base.py:84} INFO - Using connection ID 'postgres_hongheovna' for task execution.
[2024-08-07T07:55:20.297+0000] {sql.py:470} INFO - Running statement: INSERT INTO public."stgDate"(LocationKey, region_code, region_name,
                            province_code, province_name,
                            district_code, district_name,
                            ward_code, ward_name)
SELECT
	CAST(pro.province_code AS BIGINT)*100000000 + CAST(dist.district_code AS INTEGER)*100000 + CAST(w.ward_code AS INTEGER),
	re.region_code, region_name,
	pro.province_code, province_name,
	dist.district_code, district_name,
	w.ward_code, ward_name
FROM locations.region re
JOIN locations.province pro ON re.region_code = pro.region_code
JOIN locations.district dist ON dist.province_code = pro.province_code
JOIN locations.ward w ON w.district_code = dist.district_code , parameters: None
[2024-08-07T07:55:20.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T07:55:20.322+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "public.stgDate" does not exist
LINE 1: INSERT INTO public."stgDate"(LocationKey, region_code, regio...
                    ^

[2024-08-07T07:55:20.342+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=query_postgres_database, run_id=manual__2024-08-07T07:54:52.130219+00:00, execution_date=20240807T075452, start_date=20240807T075519, end_date=20240807T075520
[2024-08-07T07:55:20.386+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 186 for task query_postgres_database (relation "public.stgDate" does not exist
LINE 1: INSERT INTO public."stgDate"(LocationKey, region_code, regio...
                    ^
; 4887)
[2024-08-07T07:55:20.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T07:55:20.455+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T07:55:20.477+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
