[2024-08-09T09:38:54.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T09:38:54.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:37:56.464539+00:00 [queued]>
[2024-08-09T09:38:54.635+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:37:56.464539+00:00 [queued]>
[2024-08-09T09:38:54.636+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T09:38:54.687+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_atvsld> on 2024-08-09 09:37:56.464539+00:00
[2024-08-09T09:38:54.705+0000] {standard_task_runner.py:63} INFO - Started process 6271 to run task
[2024-08-09T09:38:54.718+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'gold_atvsld', 'manual__2024-08-09T09:37:56.464539+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmpnwzsdo7p']
[2024-08-09T09:38:54.722+0000] {standard_task_runner.py:91} INFO - Job 451: Subtask gold_atvsld
[2024-08-09T09:38:54.874+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:37:56.464539+00:00 [running]> on host 45f7764b2bf2
[2024-08-09T09:38:55.014+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='gold_atvsld' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T09:37:56.464539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T09:37:56.464539+00:00'
[2024-08-09T09:38:55.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T09:39:06.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T09:39:06.470+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/gold/atvsld_gold.py", line 36, in run_gold_atvsld
    .save()
     ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1461, in save
    self._jwrite.save()
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Table or view 'public."stgMemberSurveyFact"' already exists. SaveMode: ErrorIfExists.
[2024-08-09T09:39:06.509+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=gold_atvsld, run_id=manual__2024-08-09T09:37:56.464539+00:00, execution_date=20240809T093756, start_date=20240809T093854, end_date=20240809T093906
[2024-08-09T09:39:06.559+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 451 for task gold_atvsld (Table or view 'public."stgMemberSurveyFact"' already exists. SaveMode: ErrorIfExists.; 6271)
[2024-08-09T09:39:06.617+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-09T09:39:06.674+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T09:39:06.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
