[2024-08-09T09:30:18.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T09:30:18.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:29:21.245407+00:00 [queued]>
[2024-08-09T09:30:18.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:29:21.245407+00:00 [queued]>
[2024-08-09T09:30:18.939+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T09:30:19.001+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_atvsld> on 2024-08-09 09:29:21.245407+00:00
[2024-08-09T09:30:19.014+0000] {standard_task_runner.py:63} INFO - Started process 5185 to run task
[2024-08-09T09:30:19.019+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'gold_atvsld', 'manual__2024-08-09T09:29:21.245407+00:00', '--job-id', '433', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmpetmhh60t']
[2024-08-09T09:30:19.024+0000] {standard_task_runner.py:91} INFO - Job 433: Subtask gold_atvsld
[2024-08-09T09:30:19.126+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.gold_atvsld manual__2024-08-09T09:29:21.245407+00:00 [running]> on host 45f7764b2bf2
[2024-08-09T09:30:19.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='gold_atvsld' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T09:29:21.245407+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T09:29:21.245407+00:00'
[2024-08-09T09:30:19.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T09:30:30.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T09:30:30.592+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/gold/atvsld_gold.py", line 29, in run_gold_atvsld
    finalfact_df.write.mode("overwrite").saveAsTable('public."stgMemberSurveyFact"')
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1586, in saveAsTable
    self._jwrite.saveAsTable(name)
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near '"stgMemberSurveyFact"'.(line 1, pos 7)

== SQL ==
public."stgMemberSurveyFact"
-------^^^

[2024-08-09T09:30:30.631+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=gold_atvsld, run_id=manual__2024-08-09T09:29:21.245407+00:00, execution_date=20240809T092921, start_date=20240809T093018, end_date=20240809T093030
[2024-08-09T09:30:30.679+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 433 for task gold_atvsld (
[PARSE_SYNTAX_ERROR] Syntax error at or near '"stgMemberSurveyFact"'.(line 1, pos 7)

== SQL ==
public."stgMemberSurveyFact"
-------^^^
; 5185)
[2024-08-09T09:30:30.698+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-09T09:30:30.757+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T09:30:30.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
