[2024-08-07T15:23:40.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:23:40.735+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.refresh_stages manual__2024-08-07T15:23:24.210449+00:00 [queued]>
[2024-08-07T15:23:40.754+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.refresh_stages manual__2024-08-07T15:23:24.210449+00:00 [queued]>
[2024-08-07T15:23:40.755+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T15:23:40.793+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): refresh_stages> on 2024-08-07 15:23:24.210449+00:00
[2024-08-07T15:23:40.805+0000] {standard_task_runner.py:63} INFO - Started process 786 to run task
[2024-08-07T15:23:40.810+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'refresh_stages', 'manual__2024-08-07T15:23:24.210449+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmpwa_lw2hu']
[2024-08-07T15:23:40.814+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask refresh_stages
[2024-08-07T15:23:40.919+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.refresh_stages manual__2024-08-07T15:23:24.210449+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T15:23:41.081+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='refresh_stages' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T15:23:24.210449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T15:23:24.210449+00:00'
[2024-08-07T15:23:41.082+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:23:41.096+0000] {sql.py:276} INFO - Executing: TRUNCATE TABLE public."stgDate";
TRUNCATE TABLE public."stgDimLocation";
TRUNCATE TABLE public."stgDimFamily";
TRUNCATE TABLE public."stgDimFamilyMember";
TRUNCATE TABLE public."stgDimSurvey";

BEGIN TRANSACTION;
    INSERT INTO "DimAuditForeigned"(process_name, start_at, finished_at) VALUES
    ('data integration', NOW(), NULL);
COMMIT;
[2024-08-07T15:23:41.110+0000] {base.py:84} INFO - Using connection ID 'postgres_ldtbxh_stage' for task execution.
[2024-08-07T15:23:41.254+0000] {base.py:84} INFO - Using connection ID 'postgres_ldtbxh_stage' for task execution.
[2024-08-07T15:23:41.284+0000] {sql.py:470} INFO - Running statement: TRUNCATE TABLE public."stgDate";
TRUNCATE TABLE public."stgDimLocation";
TRUNCATE TABLE public."stgDimFamily";
TRUNCATE TABLE public."stgDimFamilyMember";
TRUNCATE TABLE public."stgDimSurvey";

BEGIN TRANSACTION;
    INSERT INTO "DimAuditForeigned"(process_name, start_at, finished_at) VALUES
    ('data integration', NOW(), NULL);
COMMIT;, parameters: None
[2024-08-07T15:23:41.392+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:23:41.393+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "DimAudit" violates not-null constraint
DETAIL:  Failing row contains (null, data integration, 2024-08-07 15:23:41.286403, null).
CONTEXT:  remote SQL command: INSERT INTO public."DimAudit"(id, process_name, start_at, finished_at) VALUES ($1, $2, $3, $4)

[2024-08-07T15:23:41.408+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=refresh_stages, run_id=manual__2024-08-07T15:23:24.210449+00:00, execution_date=20240807T152324, start_date=20240807T152340, end_date=20240807T152341
[2024-08-07T15:23:41.439+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 257 for task refresh_stages (null value in column "id" of relation "DimAudit" violates not-null constraint
DETAIL:  Failing row contains (null, data integration, 2024-08-07 15:23:41.286403, null).
CONTEXT:  remote SQL command: INSERT INTO public."DimAudit"(id, process_name, start_at, finished_at) VALUES ($1, $2, $3, $4)
; 786)
[2024-08-07T15:23:41.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T15:23:41.534+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T15:23:41.553+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
