[2024-08-07T08:19:05.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T08:19:05.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_location manual__2024-08-07T08:18:40.474458+00:00 [queued]>
[2024-08-07T08:19:05.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_location manual__2024-08-07T08:18:40.474458+00:00 [queued]>
[2024-08-07T08:19:05.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T08:19:05.748+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): bronze_location> on 2024-08-07 08:18:40.474458+00:00
[2024-08-07T08:19:05.753+0000] {standard_task_runner.py:63} INFO - Started process 5132 to run task
[2024-08-07T08:19:05.757+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'bronze_location', 'manual__2024-08-07T08:18:40.474458+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location.dag.py', '--cfg-path', '/tmp/tmp_gunwwhy']
[2024-08-07T08:19:05.760+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask bronze_location
[2024-08-07T08:19:05.834+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.bronze_location manual__2024-08-07T08:18:40.474458+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T08:19:05.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Time_Location_Dimension' AIRFLOW_CTX_TASK_ID='bronze_location' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T08:18:40.474458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T08:18:40.474458+00:00'
[2024-08-07T08:19:05.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T08:19:05.991+0000] {sql.py:276} INFO - Executing: INSERT INTO "stgDimLocation"(LocationKey, region_code, region_name,
                            province_code, province_name,
                            district_code, district_name,
                            ward_code, ward_name)
SELECT
	*
FROM dblink('dbname=atvsld password=nhanbui user=postgres port=5434', 'select * from public.vw_stgdimlocation')
AS (
	LocationKey BIGINT,
	region_code CHAR(5),
	region_name VARCHAR(50),
	province_code CHAR(5),
	province_name VARCHAR(50),
	district_code CHAR(5),
	district_name VARCHAR(50),
	ward_code CHAR(5),
	ward_name VARCHAR(50)
);
[2024-08-07T08:19:06.005+0000] {base.py:84} INFO - Using connection ID 'postgres_ldtbxh_stage' for task execution.
[2024-08-07T08:19:06.099+0000] {base.py:84} INFO - Using connection ID 'postgres_ldtbxh_stage' for task execution.
[2024-08-07T08:19:06.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T08:19:06.103+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5434 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-08-07T08:19:06.115+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=bronze_location, run_id=manual__2024-08-07T08:18:40.474458+00:00, execution_date=20240807T081840, start_date=20240807T081905, end_date=20240807T081906
[2024-08-07T08:19:06.147+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 204 for task bronze_location (connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5434 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 5132)
[2024-08-07T08:19:06.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T08:19:06.202+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T08:19:06.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
