[2024-08-02T09:56:42.132+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T09:56:42.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.query_postgres_database manual__2024-08-02T09:55:49.225553+00:00 [queued]>
[2024-08-02T09:56:42.204+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.query_postgres_database manual__2024-08-02T09:55:49.225553+00:00 [queued]>
[2024-08-02T09:56:42.205+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-02T09:56:42.251+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): query_postgres_database> on 2024-08-02 09:55:49.225553+00:00
[2024-08-02T09:56:42.256+0000] {standard_task_runner.py:63} INFO - Started process 782 to run task
[2024-08-02T09:56:42.260+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'query_postgres_database', 'manual__2024-08-02T09:55:49.225553+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmpxwzkrqpv']
[2024-08-02T09:56:42.264+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask query_postgres_database
[2024-08-02T09:56:42.355+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag.query_postgres_database manual__2024-08-02T09:55:49.225553+00:00 [running]> on host 24fc876e8f70
[2024-08-02T09:56:42.425+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'query_postgres_database', field 'sql'. Template: '../plugins/database/sql/test.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 194, in get_source
    pieces = split_template_path(template)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 35, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../plugins/database/sql/test.sql
[2024-08-02T09:56:42.428+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 194, in get_source
    pieces = split_template_path(template)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 35, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../plugins/database/sql/test.sql
[2024-08-02T09:56:42.439+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=query_postgres_database, run_id=manual__2024-08-02T09:55:49.225553+00:00, execution_date=20240802T095549, start_date=20240802T095642, end_date=20240802T095642
[2024-08-02T09:56:42.486+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task query_postgres_database (../plugins/database/sql/test.sql; 782)
[2024-08-02T09:56:42.519+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-02T09:56:42.557+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T09:56:42.587+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
